
name: Continuous Integration Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Hatch
      run: pipx install hatch
    - name: make
      run: make
    - name: make install
      run: |
          make install
          export PATH="$PWD/bin:$PATH"
    - name: Test with pytest
      run: |
          echo $PATH
          which bellhop.exe
          pwd
          ls bin/
          hatch run test:test
