name: Code Coverage Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gfortran gcc
        
    - name: Verify compiler and tools
      run: |
        gfortran --version
        gcov --version
        
    - name: Build with coverage instrumentation
      run: |
        make coverage-build
        
    - name: Install coverage-enabled executables
      run: |
        make coverage-install
        
    - name: Run tests to generate coverage data
      run: |
        make coverage-test
        
    - name: Generate coverage reports
      run: |
        make coverage-report
        
    - name: Generate HTML coverage reports for FORD integration
      run: |
        make coverage-html
        
    - name: Create coverage summary
      run: |
        echo "# Coverage Report Summary" > coverage-summary.md
        echo "" >> coverage-summary.md
        echo "## Files with Coverage Data" >> coverage-summary.md
        echo "" >> coverage-summary.md
        
        # Find all .gcov files and extract coverage stats
        echo "| File | Lines Executed | Branches Executed | Calls Executed |" >> coverage-summary.md
        echo "|------|----------------|-------------------|----------------|" >> coverage-summary.md
        
        for gcov_file in $(find . -name "*.gcov" | head -10); do
          if [ -f "$gcov_file" ]; then
            filename=$(basename "$gcov_file" .gcov)
            lines=$(grep "Lines executed:" "$gcov_file" | tail -1 | sed 's/Lines executed://' | awk '{print $1}')
            branches=$(grep "Branches executed:" "$gcov_file" | tail -1 | sed 's/Branches executed://' | awk '{print $1}')
            calls=$(grep "Calls executed:" "$gcov_file" | tail -1 | sed 's/Calls executed://' | awk '{print $1}')
            echo "| $filename | ${lines:-N/A} | ${branches:-N/A} | ${calls:-N/A} |" >> coverage-summary.md
          fi
        done
        
        echo "" >> coverage-summary.md
        echo "## Coverage Data Files Generated" >> coverage-summary.md
        echo "" >> coverage-summary.md
        echo "Total .gcda files: $(find . -name '*.gcda' | wc -l)" >> coverage-summary.md
        echo "Total .gcno files: $(find . -name '*.gcno' | wc -l)" >> coverage-summary.md  
        echo "Total .gcov files: $(find . -name '*.gcov' | wc -l)" >> coverage-summary.md
        
        cat coverage-summary.md
        
    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          **/*.gcov
          docs/*.html
          coverage-summary.md
        retention-days: 30
        
    - name: Upload coverage data
      uses: actions/upload-artifact@v4
      with:
        name: coverage-data
        path: |
          **/*.gcda
          **/*.gcno
        retention-days: 30